name: tekflat_design
description: Teko Flat Design.
version: 1.1.6-1
homepage: https://github.com/nghetien/tekflat_design

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Update lên là hẹo
  fluttertoast: ^8.2.2
  logger: ^2.0.2
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  mask_text_input_formatter: ^2.5.0
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.1.1
  collection: ^1.17.1 # Update lên là hẹo
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter: